### ISSUE TITLE
I am fan of your blog

### ISSUE THREAD

**Issue by taki** [omo/anemone.dodgson.org#2]
I am a fan of your blog. If you write some article in local then, I want to read. 

Thank you.

**Comment by omo** [comment]
Thanks you for your interest.
However, I'm not prepared to share these writings early with strangers.
That's exactly why I'm taking this awkward approach.

Don't take it personally. It's never personal to you by definition.

Again, thanks again for the comment.
I'm looking forward to sharing another batch later this year.
